### ISSUE TITLE
Retrieving files as binary via GET

### ISSUE THREAD

**Issue by kkkrist** [CianCoders/feathers-example-fileupload#2]
Hello,

thank you very much for your guide, it helped me tons. 

However I also need to be able to retrieve the files as normal binaries. How would you go about that (without utilizing the client)?

I tried to write a hook that converts the datauri back to binary and sets it as hook.result. This obviously doesn't work as you still get a json with just a binary string and content type set to application/json.

I'm still new to Feathers, hope I didn't miss anything.

**Comment by DenJohX** [comment]
Hello

I really dont have look into that as all I needed was to only upload files and process them, sorry.

Perhaps the solution is to add a middleware after the feathers service, but I'm not sure if that could work .

**Comment by DenJohX** [comment]
Actually, I have a service which responds with a file, not the same as the upload one, but it should work the same.

Basically you want to append another custom middleware, this time to get the file and write it into `res`

Like this:

``` javascript
// service that returns a binary file
  app.use('/informes', function(req, res, next){ // some custom middleware, if needed
    // some code goes here
    next()
  }, 
  new Service(), // this is the feathers service 
  function(req,res,next) {     // custom middleware to respond with a file, after the service
    // you should get the file, its mimetype and assign a filename
    res.setHeader('Content-disposition', 'attachment; filename=' + filename);
    res.setHeader('Content-type', mimetype);
    filestream.pipe(res);
  });
```

See this stackoverflow [answer](http://stackoverflow.com/questions/7288814/download-a-file-from-nodejs-server-using-express) for a more complete example of the middleware.

**Comment by kkkrist** [comment]
Thanks a lot, will try that and report back!

**Comment by kkkrist** [comment]
Had some more time looking into it today. Turns out it's even simpler with Express's res.sendFile(). This is how my upload service looks now:

``` es6
 app.use('/uploads',
    multipartMiddleware.single('uri'),
    (req, res, next) => {
      req.feathers.file = req.file
      next()
    },
    blobService,
    (req, res, next) => {
      if(req.method === "GET") {
        let file = path.join(__dirname, '../uploads', res.data.id)
        res.sendFile(file)
      } else {
        next()
      }
    }
  )
```

Thanks again for your help, much appreciated!

**Comment by DenJohX** [comment]
I completely forgot about `res.sendFile`

Glad to help!

**Comment by MarcGodard** [comment]
This is old, so something probably changed. When I go to get the id using `res.data.id` data is null. Is the data elsewhere now?

When I print out the res object, I don't see it.

**Comment by MarcGodard** [comment]
For anyone with the same issue, I got it working this way!

```javascript
    (req, res, next) => {
      if (req.method === 'GET') {
        let file = path.join(__dirname, '../../..', req.originalUrl)
        res.sendFile(file)
      } else {
        req.feathers.file = req.file
        next()
      }
```

PLEASE let me know if there is a better way.
