### ISSUE TITLE
How to authenticate uploads

### ISSUE THREAD

**Issue by eikaramba** [CianCoders/feathers-example-fileupload#4]
The article only explains how to send files as multipart via a simple form. However then i don't have any authentication(because the authentication header is missing). I want to be able to still use feathers client like app.service("uploads").create({uri:mynewUpload}). Is that even possible? Because the feathers client will likely not support multipart requests. Hence either one is encoding the data on the client OR use a simple form, but then loses all feathers mechanisms(no hooks, no authentication etc.). Isn't that right?

**Comment by eikaramba** [comment]
I managed to do this now without the feathers service, using this:

```
var form = new FormData();
    form.append('uri', $("#uri")[0].files[0]);
    if($('#myCheckbox:checked').val()) form.append('myCheckbox', true);
    form.append('anotherAttribute', XXXXXX);
    $.ajax({
      //TODO: Put it somehwere and make it dynamic
      url: "http://localhost:3030/uploads",
      method: "POST",
      dataType: 'json',
      data: form,
      beforeSend: (xhr) => {
        xhr.setRequestHeader('Authorization', this.api.get('token'));
      },
      processData: false,
      contentType: false,
      success: result => {
        
      },
      error: function(er){}
    });
```

**Comment by DenJohX** [comment]
Sorry for the late answer, but yes, the feathers client is json only. As stated on the guide you should use something else to do the uploading, that means you have to manually set the Authorization header like you did there. 

I have another example using superagent:

```javascript
import request from 'superagent'

request
    .post('/api/upload')
    .set('Authorization', token)
    .set('Accept', 'application/json')
    .attach('uri', file)  // see https://developer.mozilla.org/en-US/docs/Using_files_from_web_applications
    .on('progress', e => {
        setUploadProgress(e.percent) // show a progressbar or something
    })
    .end(function (err, res) {
        if (err || !res.ok) {
            console.log('error', arguments)  // :(
        } else {
            console.log('success!')  // done! :)
        }
    })
```
