### ISSUE TITLE
Question regarding the dropzone example

### ISSUE THREAD

**Issue by ramsestom** [CianCoders/feathers-example-fileupload#5]
On the example using dropzone I see that the upload destination is defined as  `<form action="/uploads"`. I guess this means that dropzone would directly try to contact the 'SERVER_URL/uploads' url to upload the file(s). Right?
That means that dropzone would not use the feathers client defined above, with a socket.io connection, to make the upload but rather open a new classic http connection (without any authorization header) to perform the file upload. Is it correct or am I missing something?
If so, is there any way to reuse the socket opened by the feathers client to perform the upload (without necessarily using dropzone), so that I can benefit from the autorization attached to this socket connection, or is there no curent way to perform file upload directly through scket for now?

**Comment by DenJohX** [comment]
Yep, dropzone is communicating directly with feathers without using socket.io and without authorization, but you can get the token from the feathers client and add it to the headers in dropzone.

And yes, you can use the feathers client to do the uploading but thats very unefficient, read the corresponding guide in https://github.com/feathersjs/feathers-docs/blob/master/guides/advanced/file-uploading.md for more information.
