### ISSUE TITLE
How do I customize the name of file?

### ISSUE THREAD

**Issue by rahulpatel033** [CianCoders/feathers-example-fileupload#6]
I have few questions.

1. How do I validate files ?
2. How to customize file's name ? 

seems like it takes ``${hash(content)}.${extension(contentType)}`` as a file name. How do I change it manually? let's say the name like "user-avtar-123.png".
On feathers-blob documentation I found that I just need to pass extra id field to body for custom name but I don't understand where it is used.
`const blob = {
  uri: getBase64DataURI(new Buffer('hello world'), 'text/plain')
}

blobService.create(blob).then(function (result) {
  console.log('Stored blob with id', result.id);
}).catch(err => {
  console.error(err);
});`

**Comment by DenJohX** [comment]
**How do I validate files ?**
Backend validation should be handled in one or more pre-hooks, right after the one converting the file to a base64 datauri (so doesn't matters how the file was uploaded), then you can safely reject the file before saving it with feathers-blob:

```javascript
const errors = require('feathers-errors')

// validation pre-hook
function(hook) {
    return new Promise(function(resolve, reject){
        // we need the datauri 
        if (!hook.data.uri) {
            return reject(new errors.BadRequest('Missing file'));
        }

        // validate the datauri somehow
        if (!valid){
            return reject(new errors.BadRequest('Invalid filetype'));
        }
        // if all passes then just continue to the create method
        return resolve(hook);
    }
}
```


**How to customize file's name ?**
I'm not sure about this, but by the docs the key is actually both Id and the name of the file, so you have to add it to the request, either from the frontend or again in a pre-hook:

```javascript
// filename hook
    function(hook) {
            // ... process something to generate a filename
            id = 'something.png'
            // then add it to the data, before it gets to feathers-blob
            hook.data.id = id;
        }
```

**Comment by rahulpatel033** [comment]
thanks @DenJohX, as you said to change the name I need to change the field. 
`{ 
	uri: 'base 64 string',
  	id: 'key-user-uploaded-image.png',
}` so I changed `id` and it's done.

One more thing is I can't able to add extra fields in final output response. To add custom fields I added on before create, But on final response I'm getting only three fields id, size and uri.
```
module.exports = {
    before: {
        create: [ function(hook) { 
             hook.data.id = "key-user-uploaded-image.png";
             hook.data.imageurl = "http://localhost:6789/check/"+hook.data.id+"?
             compose=1&sig=KwROfoP_7DjY&height=500&width=400";
             hook.data.temp = 1;
      }]
    },
    after: {
        create: [function(hook) { console.log(hook.data)}],
    } 
};
```

**Comment by DenJohX** [comment]
for that you need a post-hook, the `data` object is only available in pre-hooks, the response data is called  `result` and is generated by the service. Check the docs: https://docs.feathersjs.com/api/hooks.html 


--EDIT--
I correct myself, the `hook.data` is available for the post-hooks, but it's not the data returned, that is `hook.result`.

**Comment by rahulpatel033** [comment]
Oh thank you, got it. I should have checked the docs first.

**Comment by DenJohX** [comment]
Glad to help :)
